// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlatpickerController from "./flatpicker_controller.js"
application.register("flatpicker", FlatpickerController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import InputsController from "./inputs_controller.js"
application.register("inputs", InputsController)

import LoginAnimationFormController from "./login_animation_form_controller.js"
application.register("login-animation-form", LoginAnimationFormController)

import MapController from "./map_controller.js"
application.register("map", MapController)

import SearchBarController from "./search_bar_controller.js"
application.register("search-bar", SearchBarController)
